frame_stack: 4
skip_frame: 4
lr: 0.00064
min_lr: 0.00032
gamma: 0.995
max_memory: 100000
max_gradient: 10.0
epsilon: 1.0
epsilon_min: 0.1
epsilon_decay: 0.99885
batch_size: 256
update_freq: 8000
save_freq: 100000
max_frames: 10000000
window_size: 100
action_mask: []
buffer_type: "PER"
scheduler_max: 9000000
beta_start: 0.5
beta_frames: 10000