frame_stack: 4
skip_frame: 4
lr: 0.00025
min_lr: 0.00005
gamma: 0.99
max_memory: 1000000
max_gradient: 10.0
epsilon_start: 1.0
epsilon_min: 0.1
epsilon_decay_frames: 1000000
batch_size: 64
save_freq: 100000
max_frames: 10000000
window_size: 100
action_mask: []
buffer_type: "PER"
scheduler_max: 5000000
beta_start: 0.4
beta_frames: 1000000
target_update_freq: 10000
train_freq: 1
gradient_step: 64