frame_stack: 4
skip_frame: 4
lr: 0.0005
min_lr: 0.0001
gamma: 0.995
max_memory: 100000
max_gradient: 2.0
epsilon: 1.0
epsilon_min: 0.1
epsilon_decay: 0.9995
batch_size: 512
update_freq: 8000
save_freq: 8000
max_frames: 80000000
window_size: 100
action_mask: []
buffer_type: "prioritized"
scheduler_max: 1000000
beta_start: 0.5
beta_frames: 10000
